fastlane_version "1.22.0"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    #snapshot
  end

  desc "Bump"
  lane :bump do
    increment_version_number
  end

  desc "Submit a new Beta Build to Crashlytics"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh(development: true, force: true)
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    increment_build_number
    gym(
      include_bitcode: false,
    )
    crashlytics(
      notes_path: "./fastlane/metadata/en-US/version_whats_new.txt",
      crashlytics_path: "./Carthage/Build/iOS/Crashlytics.framework",
      ipa_path: "./Optonaut.ipa",
    )
    slack(
      message: "Successfully deployed new version to Crashlytics Beta."
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    sigh
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    increment_build_number
    gym
    deliver(beta: true)
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :deploy do
    snapshot
    deliver(skip_deploy: true, force: true)
    frameit
  end

end
